"""Separately implemented C34 certificate control; no registered verifier authority.
Positive lifts, embeddings, endpoint coverage and the explicit all-colour obstruction.
The exhaustive negative catalogue is regenerated by c34-check, not asserted rerun here.
"""
import base64, ctypes, ctypes.util, hashlib, itertools, json, lzma, os
import platform, resource, signal, subprocess, sys, time
from functools import lru_cache
from pathlib import Path

def need(ok,label):
    if not ok: raise ValueError(label)

def limits():
    resource.setrlimit(resource.RLIMIT_AS,(536870912,536870912))
    resource.setrlimit(resource.RLIMIT_CPU,(30,31))
    resource.setrlimit(resource.RLIMIT_FSIZE,(65536,65536))
    resource.setrlimit(resource.RLIMIT_CORE,(0,0))
    os.sched_setaffinity(0,{min(os.sched_getaffinity(0))});signal.alarm(35)
    lib=ctypes.CDLL(ctypes.util.find_library('seccomp'))
    lib.seccomp_init.argtypes=[ctypes.c_uint32];lib.seccomp_init.restype=ctypes.c_void_p
    lib.seccomp_syscall_resolve_name.argtypes=[ctypes.c_char_p]
    lib.seccomp_rule_add.argtypes=[ctypes.c_void_p,ctypes.c_uint32,ctypes.c_int,ctypes.c_uint]
    lib.seccomp_load.argtypes=[ctypes.c_void_p];lib.seccomp_release.argtypes=[ctypes.c_void_p]
    ctx=lib.seccomp_init(0x7fff0000);need(bool(ctx),'seccomp init')
    for name in (b'socket',b'socketpair',b'connect'):
        x=lib.seccomp_syscall_resolve_name(name)
        need(x>=0 and lib.seccomp_rule_add(ctx,0x00050001,x,0)==0,'seccomp rule')
    need(lib.seccomp_load(ctx)==0,'seccomp load');lib.seccomp_release(ctx)

def cyclic(A,V):
    adj={x:[] for x in V}
    for x,y in A:
        if x in adj and y in adj: adj[x].append(y)
    mark={x:0 for x in V}
    def visit(x):
        mark[x]=1
        for y in adj[x]:
            if mark[y]==1 or (mark[y]==0 and visit(y)): return True
        mark[x]=2;return False
    return any(mark[x]==0 and visit(x) for x in V)

@lru_cache(None)
def profile(arcs,n,b):
    A=set(arcs);out=[]
    for c in range(1<<n):
        classes=[{x for x in range(n) if (c>>x)&1==k} for k in (0,1)]
        if any(cyclic(A,S) for S in classes): out.append(None);continue
        relation=0
        for x in range(b):
            S=classes[(c>>x)&1];todo=[y for a,y in A if a==x and y in S];seen=set()
            while todo:
                y=todo.pop()
                if y in seen: continue
                seen.add(y);todo.extend(z for a,z in A if a==y and z in S and z not in seen)
            for y in seen:
                if y<b: relation|=1<<(b*x+y)
        out.append(relation)
    return tuple(out)

def check_rotation(A,R,B):
    R={int(k):v for k,v in R.items()};darts=set(A)|{(y,x) for x,y in A}
    need(all(x!=y and (y,x) not in A for x,y in A),'orientation')
    need(set(R)=={x for x,y in darts},'vertices')
    for x,L in R.items(): need(len(L)==len(set(L)) and set(L)=={y for a,y in darts if a==x},'neighbours')
    todo=[min(R)];vis=set()
    while todo:
        v=todo.pop()
        if v not in vis:vis.add(v);todo.extend(R[v])
    need(len(vis)==len(R),'connected')
    used=set();faces=[]
    for start in sorted(darts):
        if start in used:continue
        d=start;f=[]
        while d not in used:
            used.add(d);x,y=d;f.append(x);L=R[y];d=(y,L[(L.index(x)+1)%len(L)])
        need(d==start,'face cycle');faces.append(f)
    need(len(R)-len(A)+len(faces)==2,'spherical Euler')
    choices={tuple(B[k:]+B[:k]) for k in range(len(B))}
    need(any(tuple(f) in choices or tuple(f[::-1]) in choices for f in faces),'outer face')

def crossing(e,f):
    a,b=sorted(e);x,y=sorted(f)
    return len({a,b,x,y})==4 and ((a<x<b)!=(a<y<b))

def check_Q(rule,b):
    n=rule['vertices'];A={tuple(e) for e in rule['arcs']};tris=rule['triangles']
    need(all(x!=y and (y,x) not in A for x,y in A),'Q orientation')
    if tris is None:
        need(n==b,'only boundary sparse graph')
        chords=[e for e in A if abs(e[0]-e[1]) not in(1,b-1)]
        need(not any(crossing(e,f) for e,f in itertools.combinations(chords,2)),'disk chords')
    else:
        nxt={v:{} for v in range(n)}
        for t in list(tris)+[list(reversed(range(b)))]:
            for j,v in enumerate(t):
                need(t[j-1] not in nxt[v],'triangle corner duplicate')
                nxt[v][t[j-1]]=t[(j+1)%len(t)]
        R={}
        for v,L in nxt.items():
            start=min(L);x=start;seen=[]
            while x not in seen:seen.append(x);x=L[x]
            need(x==start and len(seen)==len(L),'vertex link');R[v]=seen
        check_rotation(A,R,list(range(b)))
    return A,n

def verify_lift(P,n,b,rule,E):
    E=set(map(tuple,E));Q,nn=check_Q(rule,b)
    need(nn<n,'strict vertex decrease')
    rim={tuple(sorted((i,(i+1)%b))) for i in range(b)}
    need({e for e in P if tuple(sorted(e)) in rim}=={e for e in Q if tuple(sorted(e)) in rim},'rim directions')
    need(not any((y,x) in Q for x,y in E),'actual exterior reverse conflict')
    pp=profile(tuple(sorted(P|E)),n,b);qq=profile(tuple(sorted(Q|E)),nn,b)
    lift=rule['lift'];need(len(lift)==len(qq),'complete lift length')
    count=0
    for c,R in enumerate(qq):
        if R is None: need(lift[c] is None,'invalid smaller assignment');continue
        d=lift[c];need(isinstance(d,int) and 0<=d<len(pp),'witness range')
        need(c&((1<<b)-1)==d&((1<<b)-1),'sigma agreement')
        need(pp[d] is not None and not pp[d]&~R,'complete reachability inclusion');count+=1
    return count

def some_cycle(A,V,c):
    for k in(0,1):
        S=[x for x in V if (c>>x)&1==k]
        for length in range(3,len(S)+1):
            for seq in itertools.permutations(S,length):
                if seq[0]==min(seq) and all((seq[j],seq[(j+1)%length]) in A for j in range(length)):
                    return {'colour':k,'cycle':list(seq)+[seq[0]]}
    raise ValueError('missing cycle')

def analyze(reports):
    counts={'geometries':0,'excluded':0,'positive_external_cases':0,'positive_assignments':0,'plain_rules':0,'endpoint_maps':0}
    endpoint_keys=set();witness=None
    for rep in reports:
        for c in rep['cases']:
            counts['geometries']+=1;A={tuple(e) for e in c['arcs']};B=c['boundary']
            check_rotation(A,c['rotation'],B)
            if c['status']=='excluded_small_semidegree':
                I=set(map(int,c['rotation']))-set(B)
                need(any(min(sum(y==v for x,y in A),sum(x==v for x,y in A))<2 for v in I),'small-semidegree exclusion')
                counts['excluded']+=1;continue
            labels=c['normalized_labels'];pos={x:i for i,x in enumerate(labels)};n=len(labels);b=len(B)
            P={(pos[x],pos[y]) for x,y in A}
            need(list(profile(tuple(sorted(P)),n,b))==c['original_profile'],'separate profile oracle')
            for rule in c['rules']:
                verify_lift(P,n,b,rule,[]);counts['plain_rules']+=1
            for e in c['exterior_cases']:
                if e['selected'] is not None:
                    counts['positive_assignments']+=verify_lift(P,n,b,e['selected'],e['exterior_arcs'])
                    counts['positive_external_cases']+=1
            if c['kind']=='fan' and c['position'] in(1,3):
                rule=next(z for z in c['rules'] if not z['guards'])
                Q={tuple(e) for e in rule['arcs']};rim={tuple(sorted((i,(i+1)%b))) for i in range(b)}
                need(not any(x<b and y<b and tuple(sorted((x,y))) not in rim for x,y in Q),'endpoint rule adds no boundary chord')
                endpoint_keys.add((tuple(c['residue']),c['position'],c['direction']));counts['endpoint_maps']+=1
            if c['residue']==[1,78] and c['kind']=='fan' and c['position']==2 and c['direction']==2:
                cert=[]
                for bits in range(8):
                    colour=sum(((bits>>j)&1)<<x for j,x in enumerate((2,4,5)))
                    cert.append({'interior_bits':bits,**some_cycle(A,list(range(7)),colour)})
                small={tuple(sorted(e)) for e in itertools.combinations(B,2)}-{tuple(sorted((B[j],B[(j+1)%4]))) for j in range(4)}
                rimA={(x,y) for x,y in A if x in B and y in B}
                for opts in itertools.product((0,1,2),repeat=len(small)):
                    Q=set(rimA)
                    for e,v in zip(sorted(small),opts):
                        if v:Q.add(e if v==1 else e[::-1])
                    need(not cyclic(Q,set(B)),'all-majority boundary completes acyclically')
                full=next(m for m in range(128) if profile(tuple(sorted(A)),7,0)[m] is not None)
                witness={'arcs':sorted(A),'rotation':c['rotation'],'boundary':B,'eight_failures':cert,'full_valid_ones_mask':full}
    need(counts['geometries']==224 and counts['excluded']==60 and counts['positive_external_cases']==420 and counts['endpoint_maps']==32,'aggregate counts')
    for res in ((1,78),(1,100),(3,43),(5,77)):
        for p in(1,3):need(sum(k[0]==res and k[1]==p for k in endpoint_keys)==4,'complete endpoint direction coverage')
    words=markings=0;maxima={}
    for d in range(6,13):
        best=0
        for word in range(1<<d):
            words+=1
            bit=lambda i:(word>>(i%d))&1
            pairs=[i for i in range(d) if bit(i)==bit(i+1) and bit(i-1)!=bit(i) and bit(i+2)!=bit(i)]
            for choice in range(1<<len(pairs)):
                chosen=[i for j,i in enumerate(pairs) if (choice>>j)&1]
                low={j%d for i in chosen for j in(i,i+1)};high={j%d for i in chosen for j in(i-1,i+2)}
                if len(low)!=2*len(chosen) or low&high:continue
                need(3*len(chosen)<=d,'disjoint pair plus high separator budget')
                markings+=1;best=max(best,len(chosen))
        maxima[d]=best
    return {'counts':counts,'obstruction':witness,'donor_word_controls':{'words':words,'valid_markings':markings,'max_t':maxima,'scope':'finite control; unrestricted packing proof is separate'}}

def main():
    need(platform.python_version()=='3.13.5','fixed Python')
    limits();start=time.monotonic();path=Path(sys.argv[1]);raw=path.read_bytes();need(len(raw)<1048576,'archive bytes')
    a=json.loads(raw);decoded=lzma.decompress(base64.b64decode(a['data']),memlimit=100000000)
    need(len(decoded)==a['decoded_bytes'] and hashlib.sha256(decoded).hexdigest()==a['decoded_sha256'],'archive identity')
    report={'verdict':'candidate_only','trusted_verifier_receipt':False,'complete':False,'source_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'input_sha256':hashlib.sha256(raw).hexdigest(),'runtime':platform.python_version()}
    try:report['results']=analyze(json.loads(decoded));report['complete']=True;code=0
    except (ValueError,KeyError,TypeError,StopIteration) as ex:report['error']=str(ex);code=1
    report['elapsed_seconds']=round(time.monotonic()-start,6);out=json.dumps(report,sort_keys=True,separators=(',',':'))+'\n';need(len(out)<65536,'output cap');print(out,end='');return code
def replay():
    D=Path('research/artifacts/candidates');O=D/'opg169-a01-c34-audit-output.json';E=D/'opg169-a01-c34-audit-stderr.txt'
    need(not O.exists() and not E.exists(),'preserve prior audit output')
    start=time.monotonic();timeout=False
    with O.open('wb') as out,E.open('wb') as err:
        p=subprocess.Popen([sys.executable,__file__,'--child',sys.argv[1]],stdout=out,stderr=err)
        try:code=p.wait(timeout=40)
        except subprocess.TimeoutExpired:p.kill();code=p.wait();timeout=True
    h=lambda b:hashlib.sha256(b).hexdigest();o,e=O.read_bytes(),E.read_bytes()
    rec={'verdict':'candidate_only','trusted_verifier_receipt':False,'runtime':platform.python_version(),
      'command':['python3',str(Path(__file__).relative_to(Path.cwd())),sys.argv[1]],'exit_code':code,'timeout':timeout,
      'elapsed_seconds':round(time.monotonic()-start,6),'source_sha256':h(Path(__file__).read_bytes()),
      'input_sha256':h(Path(sys.argv[1]).read_bytes()),'executable_sha256':h(Path(sys.executable).read_bytes()),
      'stdout_bytes':len(o),'stdout_sha256':h(o),'stderr_bytes':len(e),'stderr_sha256':h(e),
      'limits':{'memory_bytes':536870912,'cpu_seconds':30,'wall_alarm_seconds':35,'parent_timeout_seconds':40,
       'cpu_affinity_count':1,'output_file_bytes':65536,'network':'seccomp denies socket/socketpair/connect'}}
    (D/'opg169-a01-c34-audit-execution.json').write_text(json.dumps(rec,sort_keys=True,indent=2)+'\n')
    print(json.dumps(rec,sort_keys=True));return code
if __name__=='__main__':
    if len(sys.argv)>2 and sys.argv[1]=='--child':del sys.argv[1];sys.exit(main())
    sys.exit(replay())
